version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run lint
      - run: npm run test:all
  build:
    executor:
      name: node/default
    working_directory: ~/shopping-cart
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    docker:
      - image: "cimg/python:3.6"
    working_directory: ~/shopping-cart
    steps:
      - checkout
      - attach_workspace:
          at: ~/shopping-cart
      - aws-s3/sync:
          from: build
          to: "s3://$S3_BUCKET_NAME"
          overwrite: true
workflows:
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
