version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run lint
      - run: npm run test:all
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
      - run: npm run build
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
