version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-s3: circleci/aws-s3@2.0.0
jobs:
  test-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: client
      - run: cd client && npm run lint
      - run: cd client && npm run test:types
      - run: cd client && npm run test:all
  build-client:
    executor:
      name: node/default
    working_directory: ~/shopping-cart
    steps:
      - checkout
      - node/install-packages:
          app-dir: client
      - run: cd client && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - client/build
  deploy-client:
    docker:
      - image: "cimg/python:3.6"
    working_directory: ~/shopping-cart
    steps:
      - checkout
      - attach_workspace:
          at: ~/shopping-cart
      - aws-s3/sync:
          from: client/build
          to: "s3://$S3_BUCKET_NAME"
          arguments: --delete
workflows:
  build-and-deploy-client:
    jobs:
      - test-client
      - build-client:
          requires:
            - test-client
          filters:
            branches:
              only: master
      - deploy-client:
          requires:
            - build-client
          filters:
            branches:
              only: master
